# Generated by Django 4.1 on 2024-11-17 18:36

import applications.commons.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=applications.commons.utils.generate_unique_id_24char,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=applications.commons.utils.generate_unique_id_24char,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
            ],
            options={
                "db_table": "staff",
            },
        ),
    ]
